"""create_trusted_domains_and_cti_indicators

Revision ID: 76115999e53b
Revises: 
Create Date: 2026-09-22 09:06:03.414103

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '76115999e53b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cti_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('indicator', sa.String(length=2048), nullable=False, comment='Normalized indicator value (e.g. IP address, domain, or URL)'),
    sa.Column('indicator_type', sa.String(length=16), nullable=False, comment="Indicator classification: 'ip', 'url', or 'domain'"),
    sa.Column('malicious', sa.Boolean(), nullable=False, comment='Whether the indicator is confirmed malicious'),
    sa.Column('threat_score', sa.Integer(), nullable=False, comment='Severity score from 0 (benign) to 100 (critical)'),
    sa.Column('confidence', sa.Float(), nullable=False, comment='Confidence rating of the verdict (0.0 to 1.0)'),
    sa.Column('source', sa.String(length=64), nullable=False, comment='Authoritative source or feed identifier'),
    sa.Column('categories', sa.JSON(), nullable=False, comment="List of threat categories (e.g. ['phishing', 'c2', 'botnet'])"),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when threat was first observed'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when threat was most recently observed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cti_indicators_indicator'), 'cti_indicators', ['indicator'], unique=True)
    op.create_index(op.f('ix_cti_indicators_indicator_type'), 'cti_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_cti_indicators_malicious'), 'cti_indicators', ['malicious'], unique=False)
    op.create_index('ix_cti_threat_score', 'cti_indicators', ['threat_score'], unique=False)
    op.create_index('ix_cti_type_malicious', 'cti_indicators', ['indicator_type', 'malicious'], unique=False)
    op.create_table('trusted_domains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False, comment='Normalized fully qualified root domain name (lowercase)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Organization or reason for trusting this domain'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_domains_domain'), 'trusted_domains', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trusted_domains_domain'), table_name='trusted_domains')
    op.drop_table('trusted_domains')
    op.drop_index('ix_cti_type_malicious', table_name='cti_indicators')
    op.drop_index('ix_cti_threat_score', table_name='cti_indicators')
    op.drop_index(op.f('ix_cti_indicators_malicious'), table_name='cti_indicators')
    op.drop_index(op.f('ix_cti_indicators_indicator_type'), table_name='cti_indicators')
    op.drop_index(op.f('ix_cti_indicators_indicator'), table_name='cti_indicators')
    op.drop_table('cti_indicators')
    # ### end Alembic commands ###
